# Generated by Django 5.0.4 on 2024-04-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField()),
                ("cashback", models.IntegerField()),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.producttype",
                    ),
                ),
                (
                    "user_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usercard"
                    ),
                ),
            ],
            options={
                "db_table": "user_cashback",
            },
        ),
    ]
